---
apiVersion: v1
kind: Namespace
metadata:
  name: gitea

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: gitea-config
  namespace: gitea
data:
  app.ini: |
    APP_NAME = Gitea: Git with a cup of tea
    RUN_MODE = prod
    RUN_USER = gitea

    [repository]
    ROOT = /home/gitea/repositories

    [repository.local]
    LOCAL_COPY_PATH = /home/gitea/tmp/local-repo

    [repository.upload]
    TEMP_PATH = /home/gitea/uploads

    [server]
    APP_DATA_PATH    = /home/gitea
    DOMAIN           = VAR_GITEA_HOST
    SSH_DOMAIN       = VAR_GITEA_HOST
    HTTP_PORT        = 3000
    ROOT_URL         = VAR_GITEA_URL
    DISABLE_SSH      = true
    START_SSH_SERVER = false
    SSH_LISTEN_PORT  = 22
    LFS_START_SERVER = false
    OFFLINE_MODE     = false

    [database]
    PATH     = /home/gitea/gitea.db
    DB_TYPE  = sqlite3

    [indexer]
    ISSUE_INDEXER_PATH = /home/gitea/indexers/issues.bleve

    [session]
    PROVIDER_CONFIG = /home/gitea/sessions
    PROVIDER        = file

    [webhook]
    ALLOWED_HOST_LIST = internal, external, *

    [picture]
    AVATAR_UPLOAD_PATH            = /home/gitea/avatars
    REPOSITORY_AVATAR_UPLOAD_PATH = /home/gitea/repo-avatars
    DISABLE_GRAVATAR              = false
    ENABLE_FEDERATED_AVATAR       = true

    [attachment]
    PATH = /home/gitea/attachments

    [log]
    MODE      = console
    LEVEL     = info
    ROUTER    = console
    ROOT_PATH = /home/gitea/log

    [security]
    INSTALL_LOCK                  = true
    SECRET_KEY                    =
    REVERSE_PROXY_LIMIT           = 1
    REVERSE_PROXY_TRUSTED_PROXIES = *
    INTERNAL_TOKEN                = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE2NTI3MTU2MTR9.oOW1-fGDSz0X2mrThNUwpw8uioEnwh1GcgAbZsHuQ4g
    PASSWORD_HASH_ALGO            = pbkdf2

    [service]
    DISABLE_REGISTRATION              = false
    REQUIRE_SIGNIN_VIEW               = false
    REGISTER_EMAIL_CONFIRM            = false
    ENABLE_NOTIFY_MAIL                = false
    ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
    ENABLE_CAPTCHA                    = false
    DEFAULT_KEEP_EMAIL_PRIVATE        = false
    DEFAULT_ALLOW_CREATE_ORGANIZATION = true
    DEFAULT_ENABLE_TIMETRACKING       = true
    NO_REPLY_ADDRESS                  = noreply.localhost

    [mailer]
    ENABLED = false

    [openid]
    ENABLE_OPENID_SIGNIN = false
    ENABLE_OPENID_SIGNUP = false

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gosmee
  namespace: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gosmee
  template:
    metadata:
      labels:
        app: gosmee
    spec:
      containers:
        - image: ghcr.io/chmouel/gosmee:main
          imagePullPolicy: IfNotPresent
          name: gosmee
          args:
            [
              "client",
              "--saveDir",
              "/tmp/save",
              "VAR_GITEA_SMEE_HOOK_URL",
              "VAR_URL",
            ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      volumes:
        - name: gitea-config
          configMap:
            name: gitea-config
            items:
              - key: app.ini
                path: app.ini
      containers:
        - image: quay.io/gpte-devops-automation/gitea
          imagePullPolicy: IfNotPresent
          name: gitea
          env:
            - name: GITEA_HOST
              value: VAR_GITEA_HOST
            - name: GITEA_URL
              value: VAR_GITEA_URL
          ports:
            - containerPort: 3000
          volumeMounts:
            # - name: gitea-data
            #   mountPath: /home/gitea/gitea
            - name: gitea-config
              mountPath: /home/gitea/conf
          readinessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  namespace: gitea
  name: gitea
spec:
  type: NodePort
  selector:
    app: gitea
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32567
      name: http-listener
