---
apiVersion: v1
kind: Namespace
metadata:
  name: forgejo

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: forgejo-config
  namespace: forgejo
data:
  app.ini: |
    APP_NAME = Forgejo: Beyond coding. We forge.
    RUN_MODE = prod
    RUN_USER = git

    [repository]
    ROOT = /data/git/repositories

    [repository.local]
    LOCAL_COPY_PATH = /data/tmp/local-repo

    [repository.upload]
    TEMP_PATH = /data/tmp/uploads

    [oauth2]
    ENABLE = false

    [server]
    APP_DATA_PATH    = /data
    DOMAIN           = VAR_FORGEJO_HOST
    SSH_DOMAIN       = VAR_FORGEJO_HOST
    HTTP_PORT        = 3000
    ROOT_URL         = VAR_FORGEJO_URL
    DISABLE_SSH      = true
    START_SSH_SERVER = false
    SSH_LISTEN_PORT  = 22
    LFS_START_SERVER = false
    OFFLINE_MODE     = false

    [database]
    PATH     = /data/forgejo.db
    DB_TYPE  = sqlite3

    [indexer]
    ISSUE_INDEXER_PATH = /data/indexers/issues.bleve

    [session]
    PROVIDER_CONFIG = /data/sessions
    PROVIDER        = file

    [webhook]
    ALLOWED_HOST_LIST = internal, external, *

    [picture]
    AVATAR_UPLOAD_PATH            = /data/avatars
    REPOSITORY_AVATAR_UPLOAD_PATH = /data/repo-avatars
    DISABLE_GRAVATAR              = false
    ENABLE_FEDERATED_AVATAR       = true

    [attachment]
    PATH = /data/attachments

    [log]
    MODE      = console
    LEVEL     = info
    ROUTER    = console
    ROOT_PATH = /data/log

    [security]
    INSTALL_LOCK                  = true
    SECRET_KEY                    =
    REVERSE_PROXY_LIMIT           = 1
    REVERSE_PROXY_TRUSTED_PROXIES = *
    INTERNAL_TOKEN                = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE2NTI3MTU2MTR9.oOW1-fGDSz0X2mrThNUwpw8uioEnwh1GcgAbZsHuQ4g
    PASSWORD_HASH_ALGO            = pbkdf2
    MIN_PASSWORD_LENGTH           = 3

    [service]
    DISABLE_REGISTRATION              = false
    REQUIRE_SIGNIN_VIEW               = false
    REGISTER_EMAIL_CONFIRM            = false
    ENABLE_NOTIFY_MAIL                = false
    ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
    ENABLE_CAPTCHA                    = false
    DEFAULT_KEEP_EMAIL_PRIVATE        = false
    DEFAULT_ALLOW_CREATE_ORGANIZATION = true
    DEFAULT_ENABLE_TIMETRACKING       = true
    NO_REPLY_ADDRESS                  = noreply.localhost

    [mailer]
    ENABLED = false

    [openid]
    ENABLE_OPENID_SIGNIN = false
    ENABLE_OPENID_SIGNUP = false

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gosmee
  namespace: forgejo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gosmee
  template:
    metadata:
      labels:
        app: gosmee
    spec:
      containers:
        - image: ghcr.io/chmouel/gosmee:main
          imagePullPolicy: IfNotPresent
          name: gosmee
          args:
            [
              "client",
              "--saveDir",
              "/tmp/save",
              "VAR_FORGEJO_SMEE_HOOK_URL",
              "VAR_URL",
            ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo
  namespace: forgejo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forgejo
  template:
    metadata:
      labels:
        app: forgejo
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
        - name: forgejo-configmap
          configMap:
            name: forgejo-config
            items:
              - key: app.ini
                path: app.ini
        - name: forgejo-data
          emptyDir: {}
      containers:
        - image: codeberg.org/forgejo/forgejo:13
          imagePullPolicy: IfNotPresent
          name: forgejo
          env:
            - name: FORGEJO_HOST
              value: VAR_FORGEJO_HOST
            - name: FORGEJO_URL
              value: VAR_FORGEJO_URL
            - name: FORGEJO_WORK_DIR
              value: /data
            - name: FORGEJO_CUSTOM
              value: /data/gitea
          command:
            [
              "sh",
              "-c",
              "mkdir -p /data/gitea/conf && cp -f /configmap/app.ini /data/gitea/conf/app.ini && /usr/local/bin/gitea web -c /data/gitea/conf/app.ini",
            ]
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: forgejo-configmap
              mountPath: /configmap
            - name: forgejo-data
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  namespace: forgejo
  name: forgejo
spec:
  type: NodePort
  selector:
    app: forgejo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32567
      name: http-listener
