---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forgejo-ingress
  namespace: forgejo
spec:
  ingressClassName: nginx
  rules:
  - host: "forgejo.paac-127-0-0-1.nip.io"
    http:
      paths:
      - backend:
          service:
            name: "forgejo"
            port:
              number: 3000
        path: /
        pathType: Prefix
