---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: pipelines-as-code-bindings-retest-comment
  namespace: pipelines-as-code
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: pipelines-as-code
spec:
  params:
    - name: trigger_target
      value: "retest-comment"
    - name: action
      value: $(body.action)
    - name: event_type
      value: $(header.X-GitHub-Event)
    - name: owner
      value: $(body.repository.owner.login)
    - name: sender
      value: $(body.sender.login)
    - name: repository
      value: $(body.repository.name)
    - name: pull_request_url
      value: $(body.issue.pull_request.html_url)
    - name: installation_id
      value: $(body.installation.id)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipelines-as-code-template-retest-comment
  namespace: pipelines-as-code
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: pipelines-as-code
spec:
  params:
    - name: action
    - name: event_type
    - name: owner
    - name: sender
    - name: repository
    - name: pull_request_url
    - name: installation_id
    - name: trigger_target
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: pipelines-as-code-run-
        labels:
          tekton.dev/pipeline: pipelines-as-code
          tekton.dev/pipelines-as-code-event: $(tt.params.event_type)
      spec:
        serviceAccountName: pipelines-as-code-sa-el
        params:
          - name: action
            value: $(tt.params.action)
          - name: event_type
            value: $(tt.params.event_type)
          - name: owner
            value: $(tt.params.owner)
          - name: sender
            value: $(tt.params.sender)
          - name: repository
            value: $(tt.params.repository)
          - name: pull_request_url
            value: $(tt.params.pull_request_url)
          - name: installation_id
            value: $(tt.params.installation_id)
          - name: trigger_target
            value: $(tt.params.trigger_target)
        pipelineSpec:
          params:
            - name: action
            - name: trigger_target
            - name: event_type
            - name: owner
            - name: sender
            - name: repository
            - name: pull_request_url
            - name: installation_id
          workspaces:
            - name: secrets
          tasks:
            - name: get-token
              taskRef:
                name: github-app-token
              params:
                - name: installation_id
                  value: $(params.installation_id)
              workspaces:
                - name: secrets
                  workspace: secrets
            - name: pipelines-as-code
              runAfter: [get-token]
              taskSpec:
                params:
                  - name: action
                    type: string
                  - name: event_type
                    type: string
                  - name: owner
                    type: string
                  - name: sender
                    type: string
                  - name: repository
                    type: string
                  - name: pull_request_url
                    type: string
                  - name: token
                    type: string
                  - name: trigger_target
                    type: string
                steps:
                  - name: apply-and-launch
                    image: "ko://github.com/openshift-pipelines/pipelines-as-code/cmd/pipelines-as-code"
                    script: |
                      cat << EOF > /tmp/payload.json
                      {
                        "action": "$(params.action)",
                        "issue": {
                          "pull_request": {
                            "html_url": "$(params.pull_request_url)"
                          }
                        },
                        "sender": {
                           "login": "$(params.sender)"
                         },
                        "repository": {
                            "name": "$(params.repository)",
                            "owner": {
                              "login": "$(params.owner)"
                            }
                        }
                      }
                      EOF
                      pipelines-as-code --trigger-target=$(params.trigger_target) \
                        --payload-file=/tmp/payload.json --token="$(params.token)" --webhook-type="$(params.event_type)"
              params:
                - name: action
                  value: "$(params.action)"
                - name: trigger_target
                  value: "$(params.trigger_target)"
                - name: event_type
                  value: "$(params.event_type)"
                - name: owner
                  value: "$(params.owner)"
                - name: sender
                  value: "$(params.sender)"
                - name: repository
                  value: "$(params.repository)"
                - name: pull_request_url
                  value: "$(params.pull_request_url)"
                - name: token
                  value: "$(tasks.get-token.results.token)"
        workspaces:
          - name: secrets
            secret:
              secretName: github-app-secret
