name: Build and publish Muilti-arch images to ghcr

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

env:
  REGISTRY: ghcr.io
  CONTROLLER_IMAGE_NAME: ${{ github.repository }}-controller
  WATCHER_IMAGE_NAME: ${{ github.repository }}-watcher
  WEBHOOK_IMAGE_NAME: ${{ github.repository }}-webhook
  TKN_PAC_IMAGE_NAME: ${{ github.repository }}-tkn-pac

jobs:
  build-and-push-multiarch-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker (Controller)
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.CONTROLLER_IMAGE_NAME }}

      - name: Build and push controller docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          build-args: |
            BINARY_NAME=pipelines-as-code-controller
          platforms: linux/amd64,linux/ppc64le,linux/s390x
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Extract metadata (tags, labels) for Docker (Watcher)
        id: meta-watcher
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.WATCHER_IMAGE_NAME }}

      - name: Build and push watcher docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          build-args: |
            BINARY_NAME=pipelines-as-code-watcher
          platforms: linux/amd64,linux/ppc64le,linux/s390x
          push: true
          tags: ${{ steps.meta-watcher.outputs.tags }}
          labels: ${{ steps.meta-watcher.outputs.labels }}

      - name: Extract metadata (tags, labels) for Docker (Webhook)
        id: meta-webhook
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.WEBHOOK_IMAGE_NAME }}

      - name: Build and push webhook docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          build-args: |
            BINARY_NAME=pipelines-as-code-webhook
          platforms: linux/amd64,linux/ppc64le,linux/s390x
          push: true
          tags: ${{ steps.meta-webhook.outputs.tags }}
          labels: ${{ steps.meta-webhook.outputs.labels }}

      - name: Extract metadata (tags, labels) for tkn-pac
        id: meta-cli
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.TKN_PAC_IMAGE_NAME }}

      - name: Build and push cli docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          build-args: |
            BINARY_NAME=tkn-pac
          platforms: linux/amd64,linux/ppc64le,linux/s390x
          push: true
          tags: ${{ steps.meta-cli.outputs.tags }}
          labels: ${{ steps.meta-cli.outputs.labels }}
