name: Create and publish a Docker image to ghcr

on: ["push"]

env:
  REGISTRY: ghcr.io
  CONTROLLER_IMAGE_NAME: ${{ github.repository }}-controller
  WATCHER_IMAGE_NAME: ${{ github.repository }}-watcher
  WEBHOOK_IMAGE_NAME: ${{ github.repository }}-webhook
  TKN_PAC_IMAGE_NAME: ${{ github.repository }}-tkn-pac

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker (Controller)
        id: meta
        uses: docker/metadata-action@2c0bd771b40637d97bf205cbccdd294a32112176
        with:
          images: ${{ env.REGISTRY }}/${{ env.CONTROLLER_IMAGE_NAME }}

      - name: Build and push controller docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          build-args: |
            BINARY_NAME=pipelines-as-code-controller
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Extract metadata (tags, labels) for Docker (Watcher)
        id: meta-watcher
        uses: docker/metadata-action@2c0bd771b40637d97bf205cbccdd294a32112176
        with:
          images: ${{ env.REGISTRY }}/${{ env.WATCHER_IMAGE_NAME }}

      - name: Build and push watcher docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          build-args: |
            BINARY_NAME=pipelines-as-code-watcher
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta-watcher.outputs.tags }}
          labels: ${{ steps.meta-watcher.outputs.labels }}

      - name: Extract metadata (tags, labels) for Docker (Webhook)
        id: meta-webhook
        uses: docker/metadata-action@2c0bd771b40637d97bf205cbccdd294a32112176
        with:
          images: ${{ env.REGISTRY }}/${{ env.WEBHOOK_IMAGE_NAME }}

      - name: Build and push webhook docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          build-args: |
            BINARY_NAME=pipelines-as-code-webhook
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta-webhook.outputs.tags }}
          labels: ${{ steps.meta-webhook.outputs.labels }}

      - name: Extract metadata (tags, labels) for tkn-pac
        id: meta-cli
        uses: docker/metadata-action@2c0bd771b40637d97bf205cbccdd294a32112176
        with:
          images: ${{ env.REGISTRY }}/${{ env.TKN_PAC_IMAGE_NAME }}

      - name: Build and push cli docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          build-args: |
            BINARY_NAME=tkn-pac
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta-cli.outputs.tags }}
          labels: ${{ steps.meta-cli.outputs.labels }}
